# Upstox access token - can be updated from the frontend via API.
# Do not commit this file with a real token (see .gitignore).
UPSTOX_ACCESS_TOKEN = 'eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiI1OENTTDkiLCJqdGkiOiI2OWM3OTMwNzQwNmM3NTY5Nzk1Y2QwMDEiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6dHJ1ZSwiaWF0IjoxNzc0Njg2OTgzLCJpc3MiOiJ1ZGFwaS1nYXRld2F5LXNlcnZpY2UiLCJleHAiOjE3NzQ3MzUyMDB9.R7cmm-WgUTzGddy5gfWirWuUiDIbVgJFNh5VtkZYCRU'
