# Upstox access token - can be updated from the frontend via API.
# Do not commit this file with a real token (see .gitignore).
UPSTOX_ACCESS_TOKEN = 'eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiI2OUJWREwiLCJqdGkiOiI2OTlkMzkwZjExZmU1MzdmMjBkOTU1ZTgiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6dHJ1ZSwiaWF0IjoxNzcxOTExNDM5LCJpc3MiOiJ1ZGFwaS1nYXRld2F5LXNlcnZpY2UiLCJleHAiOjE3NzE5NzA0MDB9.nizsLINZjQrKNV3enlnizTNTovSsEtb93H2Fhw4TziE'
