# Upstox access token - can be updated from the frontend via API.
# Do not commit this file with a real token (see .gitignore).
UPSTOX_ACCESS_TOKEN = 'eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiI2OUJWREwiLCJqdGkiOiI2OWEyOTgyZTU3NDY0OTRiNzVjMDA3YzMiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6dHJ1ZSwiaWF0IjoxNzcyMjYzNDcwLCJpc3MiOiJ1ZGFwaS1nYXRld2F5LXNlcnZpY2UiLCJleHAiOjE3NzIzMTYwMDB9.Qa-Itdic4g863RLsXKLOYeXgwggZVH7Z1XOr5vpeVLs'
