# Upstox access token - can be updated from the frontend via API.
# Do not commit this file with a real token (see .gitignore).
UPSTOX_ACCESS_TOKEN = 'eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiI2OUJWREwiLCJqdGkiOiI2OWUwNjYwNGE0MWE5NjQyYjdiMjM4NDIiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6dHJ1ZSwiaWF0IjoxNzc2MzEzODYwLCJpc3MiOiJ1ZGFwaS1nYXRld2F5LXNlcnZpY2UiLCJleHAiOjE3NzYzNzY4MDB9.Sp2IJYWKZnoJ17a1Yh-hbERsMvm1Oi-Co_cIStE0V-8'
